DOMAIN-KEYWORD,keenetic
DOMAIN-KEYWORD,netcraze
DOMAIN-SUFFIX,dataplicity.com
DOMAIN-SUFFIX,gmail.com
DOMAIN-SUFFIX,yastatic.net
DOMAIN-SUFFIX,yandex.com
DOMAIN-SUFFIX,yandex.net
DOMAIN-SUFFIX,yandex.ru
DOMAIN-SUFFIX,gosuslugi.ru
DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,apple.com
IP-ASN,1042
IP-ASN,31128
IP-ASN,6185
IP-ASN,714
IP-CIDR,31.56.208.250/32
