DOMAIN-KEYWORD,keenetic
DOMAIN-KEYWORD,netcraze
DOMAIN-SUFFIX,dataplicity.com
DOMAIN-SUFFIX,gmail.com
DOMAIN-SUFFIX,yastatic.net
DOMAIN-SUFFIX,yandex.com
DOMAIN-SUFFIX,yandex.net
DOMAIN-SUFFIX,yandex.ru
DOMAIN-SUFFIX,gosuslugi.ru
DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,apple.com
DOMAIN-SUFFIX,apple-cloudkit.com
DOMAIN-SUFFIX,cdn-apple.com
DOMAIN-SUFFIX,ru
DOMAIN-SUFFIX,su
DOMAIN-SUFFIX,рф
DOMAIN-SUFFIX,xn--p1ai
DOMAIN-KEYWORD,.ru
DOMAIN-KEYWORD,.su
DOMAIN-KEYWORD,.рф
DOMAIN-KEYWORD,.xn--p1ai
IP-CIDR,31.56.208.250/32
