IP-CIDR,1.1.1.1/32
IP-CIDR,8.8.8.8/32
IP-CIDR,9.9.9.9/32
DOMAIN-SUFFIX,https://dns.quad9.net/dns-query
DOMAIN-SUFFIX,https://dns.adguard-dns.com/dns-query
DOMAIN-SUFFIX,https://dns.cloudflare.com/dns-query
DOMAIN-SUFFIX,https://dns.google/dns-query
