DOMAIN-SUFFIX,garmincdn.com
DOMAIN-SUFFIX,garmin.com
DOMAIN-SUFFIX,ntc.party
IP-CIDR,30.255.77.28/32
IP-CIDR,130.255.77.28/32
DOMAIN-SUFFIX,usercontent.dev
DOMAIN-SUFFIX,tx.me
DOMAIN-SUFFIX,ton.org
DOMAIN-SUFFIX,tg.dev
DOMAIN-SUFFIX,telesco.pe
DOMAIN-SUFFIX,telegram.space
DOMAIN-SUFFIX,telegram.org
DOMAIN-SUFFIX,telegram.me
DOMAIN-SUFFIX,telegram.dog
DOMAIN-SUFFIX,telegram-cdn.org
DOMAIN-SUFFIX,telegra.ph
DOMAIN-SUFFIX,telega.one
DOMAIN-SUFFIX,tdesktop.com
DOMAIN-SUFFIX,t.me
DOMAIN-SUFFIX,quiz.directory
DOMAIN-SUFFIX,graph.org
DOMAIN-SUFFIX,fragment.com
DOMAIN-SUFFIX,contest.com
DOMAIN-SUFFIX,comments.app
DOMAIN-SUFFIX,cdn-telegram.org
IP-CIDR,185.76.151.0/24
IP-CIDR,91.108.20.0/22
IP-CIDR,91.105.192.0/23
IP-CIDR,149.154.160.0/20
IP-CIDR,91.108.12.0/22
IP-CIDR,91.108.16.0/22
IP-CIDR,91.108.8.0/22
IP-CIDR,91.108.4.0/22
IP-CIDR,91.108.56.0/22
