[General]
dns-server = https://dns.quad9.net/dns-query,https://dns.google/dns-query
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-direct-system = true
dns-fallback-system = true
dns-direct-fallback-proxy = false
fallback-dns-server = tls://common.dot.dns.yandex.net,system
hijack-dns = :53
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32,31.56.208.250/32
always-real-ip = *.lan,*.local,*.home,time.*.com,time.*.apple.com,time-ios.apple.com,*.ntp.org,ntp.*.com
icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/main/ru_geo_test.conf
interval = 259200

[Rule]
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/block.list,REJECT
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/proxy.list,PROXY
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/proxy-ip.list,PROXY,no-resolve
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/direct-ip.list,DIRECT,no-resolve
DOMAIN-SUFFIX,alfa-bank.net,DIRECT
DOMAIN-SUFFIX,alfaintra.net,DIRECT
DOMAIN-SUFFIX,rasswet.site,DIRECT
DOMAIN-SUFFIX,achat.best,DIRECT
#GEOIP,RU,DIRECT
FINAL,PROXY

[Host]
localhost = 127.0.0.1

[MITM]
enable = false
