[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true
dns-server = https://dns.quad9.net/dns-query, https://dns.adguard-dns.com/dns-query, https://dns.cloudflare.com/dns-query, https://dns.google/dns-query
fallback-dns-server = system
hijack-dns = :53
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com,*.ru,*.su,*.рф,*.xn--p1ai
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32
always-real-ip = *.lan,*.local,*.home,time.*.com,time.*.apple.com,time-ios.apple.com,*.ntp.org,ntp.*.com
icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/main/ru_geo.conf

[Host]
ai.google.dev = 45.155.204.190
aisandbox-pa.googleapis.com = 45.155.204.190
aistudio.google.com = 45.155.204.190
aitestkitchen.withgoogle.com = 45.155.204.190
alkalicore-pa.clients6.google.com = 45.155.204.190
alkalimakersuite-pa.clients6.google.com = 45.155.204.190
apis.google.com = 45.155.204.190
appcatalyst.pa.googleapis.com = 45.155.204.190
assistant-s3-pa.googleapis.com = 45.155.204.190
bard.google.com = 45.155.204.190
daily-cloudcode-pa.googleapis.com = 45.155.204.190
deepmind.com = 45.155.204.190
deepmind.google = 45.155.204.190
developerprofiles-pa.googleapis.com = 45.155.204.190
geller-pa.googleapis.com = 45.155.204.190
gemini.google = 45.155.204.190
gemini.google.com = 45.155.204.190
generativeai.google = 45.155.204.190
generativelanguage.googleapis.com = 45.155.204.190
jules.google = 45.155.204.190
jules.google.com = 45.155.204.190
labs.google = 45.155.204.190
labs.google.com = 45.155.204.190
lookerstudio.google.com = 45.155.204.190
makersuite.google.com = 45.155.204.190
notebooklm-pa.googleapis.com = 45.155.204.190
notebooklm.google = 45.155.204.190
notebooklm.google.com = 45.155.204.190
o.pki.goog = 45.155.204.190
opal.google = 45.155.204.190
opal.google.com = 45.155.204.190
opal.withgoogle.com = 45.155.204.190
people-pa.clients6.google.com = 45.155.204.190
proactivebackend-pa.googleapis.com = 45.155.204.190
robinfrontend-pa.googleapis.com = 45.155.204.190
signaler-pa.clients6.google.com = 45.155.204.190
stitch.withgoogle.com = 45.155.204.190
waa-pa.clients6.google.com = 45.155.204.190
webchannel-alkalimakersuite-pa.clients6.google.com = 45.155.204.190
localhost = 127.0.0.1

[Rule]
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/adblock_rule_set.conf,REJECT
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/direct.conf,DIRECT
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/proxy.conf,PROXY
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/dns.conf,PROXY
RULE-SET,https://raw.githubusercontent.com/Shurik85/Shadowrocket-AdBlock/refs/heads/main/shadowrocket_telegram.conf,PROXY
GEOIP,RU,DIRECT
FINAL,PROXY

[MITM]
enable = false
