name: Update Shadowrocket Rules

on:
  schedule:
    - cron: '0 3 * * *' # Запуск каждый день в 3:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          python -m pip install --upgrade pip
          pip install protobuf

      - name: Run build script
        run: python build.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Добавляем все пять файлов конфигураций
          git add direct.list proxy.list block.list direct-ip.list proxy-ip.list
          if git diff --cached --quiet; then
            echo "Изменений нет."
          else
            git commit -m "Auto-update rules: $(date +'%Y-%m-%d')"
            git push
          fi
